# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='myrank',
            field=models.FloatField(default=0.0),
        ),
    ]
